allowBuilds:
  esbuild: true
  "@embedded-postgres/windows-x64": true
  "@embedded-postgres/linux-x64": true
  "@embedded-postgres/linux-arm64": true
  "@embedded-postgres/darwin-x64": true
  "@embedded-postgres/darwin-arm64": true
