CREATE TABLE admins(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),singleton boolean NOT NULL DEFAULT true UNIQUE CHECK(singleton),password_hash text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
INSERT INTO admins(id,password_hash,created_at,updated_at) SELECT id,password_hash,created_at,updated_at FROM users WHERE role='admin' ORDER BY created_at,id LIMIT 1;
CREATE TABLE profiles(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name varchar(64) NOT NULL UNIQUE,is_active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
INSERT INTO profiles(id,name,is_active,created_at,updated_at) SELECT id,username,is_active,created_at,updated_at FROM users WHERE role='user';
CREATE TABLE functions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),def_number integer NOT NULL UNIQUE CHECK(def_number>0),slug varchar(32) NOT NULL UNIQUE,title varchar(200) NOT NULL,is_active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CHECK(slug='def'||def_number::text));
INSERT INTO functions(def_number,slug,title,created_at,updated_at) SELECT DISTINCT ON(e.def_number) e.def_number,e.slug,COALESCE(NULLIF(e.title,''),e.slug),e.created_at,e.updated_at FROM entries e JOIN profiles p ON p.id=e.user_id ORDER BY e.def_number,e.created_at,e.id;
CREATE TABLE variants(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),profile_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,function_id uuid NOT NULL REFERENCES functions(id) ON DELETE CASCADE,content text NOT NULL,is_active boolean NOT NULL DEFAULT true,expires_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(profile_id,function_id));
CREATE INDEX variants_function ON variants(function_id);
INSERT INTO variants(id,profile_id,function_id,content,is_active,expires_at,created_at,updated_at) SELECT e.id,e.user_id,f.id,e.content,e.is_active,e.expires_at,e.created_at,e.updated_at FROM entries e JOIN profiles p ON p.id=e.user_id JOIN functions f ON f.def_number=e.def_number;
CREATE TABLE function_counter(singleton boolean PRIMARY KEY DEFAULT true CHECK(singleton),next_number integer NOT NULL DEFAULT 1 CHECK(next_number>0));
INSERT INTO function_counter(next_number) SELECT GREATEST(COALESCE((SELECT max(next_def_number) FROM users),1),COALESCE((SELECT max(def_number)+1 FROM functions),1));
DROP TABLE sessions;
CREATE TABLE sessions(token_hash text PRIMARY KEY,admin_id uuid NOT NULL REFERENCES admins(id) ON DELETE CASCADE,csrf_token text NOT NULL,expires_at timestamptz NOT NULL);
CREATE INDEX sessions_admin ON sessions(admin_id);
CREATE INDEX sessions_expiry ON sessions(expires_at);
ALTER TABLE audit_logs ADD COLUMN target_function_id uuid;
DROP TABLE entries;
DROP TABLE users;
DELETE FROM login_limits;
